[ 2023-04-23 16:57:56,812 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 16:57:56,812 ] root - INFO - Starting data ingestion
[ 2023-04-23 16:57:56,832 ] root - INFO - Consider Local csv file
[ 2023-04-23 16:57:57,969 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 16:57:58,048 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 16:57:58,048 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_16_57_56/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 16:57:59,092 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 16:57:59,092 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 16:58:01,050 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_16_57_56/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_16_57_56/data_ingestion/ingested/test.csv')
[ 2023-04-23 16:58:02,353 ] root - INFO - Missing numerical column: []
[ 2023-04-23 16:58:02,353 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 16:58:02,353 ] root - INFO - Missing numerical column: []
[ 2023-04-23 16:58:02,353 ] root - INFO - Required number of columns: 164
[ 2023-04-23 16:58:02,353 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 16:58:02,353 ] root - INFO - Required number of columns: 164
[ 2023-04-23 16:58:02,354 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 16:58:07,554 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=False, valid_train_file_path='artifact/04_23_2023_16_57_56/data_ingestion/ingested/train.csv', valid_test_file_path='artifact/04_23_2023_16_57_56/data_ingestion/ingested/test.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact/04_23_2023_16_57_56/data_validation/drift_report/report.yaml')
[ 2023-04-23 16:58:08,556 ] root - INFO - Error occurred python script name [main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [82] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [60] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_transformation.py] line number [73] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_transformation.py] line number [55] error message [name 'FunctionTransformer' is not defined]]]]]
