[ 2023-04-23 04:31:31,387 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 04:31:31,387 ] root - INFO - Starting data ingestion
[ 2023-04-23 04:31:31,408 ] root - INFO - Consider Local csv file
[ 2023-04-23 04:31:32,490 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 04:31:32,562 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:31:32,562 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_04_31_30/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 04:31:33,417 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:31:33,417 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 04:31:35,011 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_04_31_30/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_04_31_30/data_ingestion/ingested/test.csv')
[ 2023-04-23 04:31:35,031 ] root - INFO - Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [79] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [49] error message ['DataValidation' object has no attribute 'initiate_data_validation']]]
