[ 2023-04-23 04:21:02,097 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 04:21:02,097 ] root - INFO - Starting data ingestion
[ 2023-04-23 04:21:02,116 ] root - INFO - Consider Local csv file
[ 2023-04-23 04:21:03,131 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 04:21:03,207 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:21:03,207 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_04_21_01/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 04:21:03,942 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:21:03,942 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 04:21:05,704 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_04_21_01/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_04_21_01/data_ingestion/ingested/test.csv')
[ 2023-04-23 04:21:05,725 ] root - INFO - Error occurred python script name [main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [79] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [49] error message ['DataValidation' object has no attribute 'initialize_data_validation']]]
