[ 2023-04-23 00:02:11,233 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 00:02:11,234 ] root - INFO - Starting data ingestion
[ 2023-04-23 00:02:11,258 ] root - INFO - Consider Local csv file
[ 2023-04-23 00:02:12,847 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 00:02:12,964 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 00:02:12,964 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_00_02_10/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 00:02:14,123 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 00:02:14,123 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 00:02:15,999 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_00_02_10/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_00_02_10/data_ingestion/ingested/test.csv')
[ 2023-04-23 00:02:16,972 ] root - INFO - Missing numerical column: []
[ 2023-04-23 00:02:16,973 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 00:02:16,973 ] root - INFO - Missing numerical column: []
[ 2023-04-23 00:02:16,973 ] root - INFO - Required number of columns: 164
[ 2023-04-23 00:02:16,973 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 00:02:16,973 ] root - INFO - Required number of columns: 164
[ 2023-04-23 00:02:16,973 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 00:02:20,066 ] root - INFO - Error occurred python script name [main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [69] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [48] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_validation.py] line number [182] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_validation.py] line number [122] error message ['<' not supported between instances of 'float' and 'str']]]]]
