[ 2023-04-23 04:09:44,202 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 04:09:44,202 ] root - INFO - Starting data ingestion
[ 2023-04-23 04:09:44,222 ] root - INFO - Consider Local csv file
[ 2023-04-23 04:09:45,474 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 04:09:45,542 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:09:45,542 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_04_09_43/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 04:09:46,268 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:09:46,268 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 04:09:47,684 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_04_09_43/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_04_09_43/data_ingestion/ingested/test.csv')
[ 2023-04-23 04:09:48,655 ] root - INFO - Missing numerical column: []
[ 2023-04-23 04:09:48,655 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 04:09:48,655 ] root - INFO - Missing numerical column: []
[ 2023-04-23 04:09:48,656 ] root - INFO - Required number of columns: 164
[ 2023-04-23 04:09:48,656 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 04:09:48,656 ] root - INFO - Required number of columns: 164
[ 2023-04-23 04:09:48,656 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 04:09:49,270 ] root - INFO - Error occurred python script name [main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [79] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [49] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_validation.py] line number [183] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_validation.py] line number [122] error message ['<' not supported between instances of 'int' and 'str']]]]]
