[ 2023-04-23 22:22:57,250 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 22:22:57,251 ] root - INFO - Starting data ingestion
[ 2023-04-23 22:22:57,271 ] root - INFO - Consider Local csv file
[ 2023-04-23 22:22:58,701 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 22:22:58,798 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 22:22:58,799 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_22_22_56/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 22:22:59,772 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 22:22:59,772 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 22:23:01,612 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_22_22_56/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_22_22_56/data_ingestion/ingested/test.csv')
[ 2023-04-23 22:23:03,067 ] root - INFO - Missing numerical column: []
[ 2023-04-23 22:23:03,068 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 22:23:03,068 ] root - INFO - Missing numerical column: []
[ 2023-04-23 22:23:03,068 ] root - INFO - Required number of columns: 164
[ 2023-04-23 22:23:03,068 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 22:23:03,068 ] root - INFO - Required number of columns: 164
[ 2023-04-23 22:23:03,068 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 22:23:09,528 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=False, valid_train_file_path='artifact/04_23_2023_22_22_56/data_ingestion/ingested/train.csv', valid_test_file_path='artifact/04_23_2023_22_22_56/data_ingestion/ingested/test.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact/04_23_2023_22_22_56/data_validation/drift_report/report.yaml')
[ 2023-04-23 22:23:59,875 ] root - INFO - Entered the save_object method of MainUtils class
[ 2023-04-23 22:23:59,913 ] root - INFO - Exited the save_object method of MainUtils class
[ 2023-04-23 22:23:59,914 ] root - INFO - Data transformation artifact: DataTransformationArtifact(transformed_object_file_path='artifact/04_23_2023_22_22_56/data_transformation/transformed_object/preprocessing.pkl', transformed_train_file_path='artifact/04_23_2023_22_22_56/data_transformation/transformed/train.npy', transformed_test_file_path='artifact/04_23_2023_22_22_56/data_transformation/transformed/test.npy')
[ 2023-04-23 22:24:22,271 ] root - INFO - Entered the load_object method of MainUtils class
[ 2023-04-23 22:24:22,272 ] root - INFO - Exited the load_object method of MainUtils class
[ 2023-04-23 22:24:22,273 ] root - INFO - Entered the save_object method of MainUtils class
[ 2023-04-23 22:24:22,289 ] root - INFO - Exited the save_object method of MainUtils class
[ 2023-04-23 22:24:22,289 ] root - INFO - Error occurred python script name [main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [94] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [74] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/model_trainer.py] line number [71] error message [__init__() got an unexpected keyword argument 'train_metric_artifact']]]]
