[ 2023-04-23 16:00:14,396 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 16:00:14,397 ] root - INFO - Starting data ingestion
[ 2023-04-23 16:00:14,523 ] root - INFO - Consider Local csv file
[ 2023-04-23 16:00:15,808 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 16:00:15,879 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 16:00:15,879 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_16_00_07/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 16:00:16,863 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 16:00:16,864 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 16:00:18,628 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_16_00_07/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_16_00_07/data_ingestion/ingested/test.csv')
[ 2023-04-23 16:00:21,483 ] root - INFO - Missing numerical column: []
[ 2023-04-23 16:00:21,484 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 16:00:21,485 ] root - INFO - Missing numerical column: []
[ 2023-04-23 16:00:21,485 ] root - INFO - Required number of columns: 164
[ 2023-04-23 16:00:21,485 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 16:00:21,485 ] root - INFO - Required number of columns: 164
[ 2023-04-23 16:00:21,485 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 16:00:47,183 ] root - INFO - Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [80] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [49] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_validation.py] line number [177] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_validation.py] line number [117] 
error message ['<' not supported between instances of 'float' and 'str']]]]]
