[ 2023-04-23 22:10:47,570 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 22:10:47,570 ] root - INFO - Starting data ingestion
[ 2023-04-23 22:10:47,591 ] root - INFO - Consider Local csv file
[ 2023-04-23 22:10:48,703 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 22:10:48,763 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 22:10:48,764 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_22_10_46/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 22:10:49,705 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 22:10:49,705 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 22:10:51,464 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_22_10_46/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_22_10_46/data_ingestion/ingested/test.csv')
[ 2023-04-23 22:10:52,732 ] root - INFO - Missing numerical column: []
[ 2023-04-23 22:10:52,732 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 22:10:52,732 ] root - INFO - Missing numerical column: []
[ 2023-04-23 22:10:52,732 ] root - INFO - Required number of columns: 164
[ 2023-04-23 22:10:52,732 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 22:10:52,732 ] root - INFO - Required number of columns: 164
[ 2023-04-23 22:10:52,732 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 22:10:58,002 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=False, valid_train_file_path='artifact/04_23_2023_22_10_46/data_ingestion/ingested/train.csv', valid_test_file_path='artifact/04_23_2023_22_10_46/data_ingestion/ingested/test.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact/04_23_2023_22_10_46/data_validation/drift_report/report.yaml')
[ 2023-04-23 22:11:22,838 ] root - INFO - Entered the save_object method of MainUtils class
[ 2023-04-23 22:11:22,856 ] root - INFO - Exited the save_object method of MainUtils class
[ 2023-04-23 22:11:22,863 ] root - INFO - Data transformation artifact: DataTransformationArtifact(transformed_object_file_path='artifact/04_23_2023_22_10_46/data_transformation/transformed_object/preprocessing.pkl', transformed_train_file_path='artifact/04_23_2023_22_10_46/data_transformation/transformed/train.npy', transformed_test_file_path='artifact/04_23_2023_22_10_46/data_transformation/transformed/test.npy')
[ 2023-04-23 22:11:23,008 ] root - INFO - Error occurred python script name [main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [94] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [74] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/model_trainer.py] 
line number [34] error message [type object 'DataTransformationArtifact' has no attribute 'transformed_train_file_path']]]]
